dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
language: csharp
mono: none
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet --version
  - dotnet build
  - dotnet publish -r osx.10.12-x64 -c Release /p:PublishSingleFile=true
  - dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true